// <auto-generated />
using System;
using JobPrepAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPrepAPI.Migrations
{
    [DbContext(typeof(JobDbContext))]
    [Migration("20250409133219_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobPrepAPI.Entities.JobDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DescriptionText")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__JobDescr__3214EC0701A9311D");

                    b.ToTable("JobDescriptions");
                });

            modelBuilder.Entity("JobPrepAPI.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("JobDescriptionId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK__Question__3214EC07E480BB23");

                    b.HasIndex("JobDescriptionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("JobPrepAPI.Entities.Question", b =>
                {
                    b.HasOne("JobPrepAPI.Entities.JobDescription", "JobDescription")
                        .WithMany("Questions")
                        .HasForeignKey("JobDescriptionId")
                        .HasConstraintName("FK__Questions__JobDe__4BAC3F29");

                    b.Navigation("JobDescription");
                });

            modelBuilder.Entity("JobPrepAPI.Entities.JobDescription", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
